# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1913acb2fea33539f371c3b62faa717fc87fab7c6df627f6865c5d037ea413b07bcbbb390faa2d5a45f2ae5f0fcf63a0ca73d35ed6a82a5c68fa83e2bc38a217

test:
  secret_key_base: 696a9ef34f6c3ea47fb7a7058fb222598f8f737c85c73f5ea18f903554a6701ea3572b083e6624d035ef86a71cb624e976bbe34aa8bfbc80ab685c335816bfff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
